db:
  database: ads_microservice_production
  url: <%= ENV.fetch('ADS_DATABASE_URL') %>
rabbitmq:
  host: <%= ENV.fetch('RABBITMQ_HOST') %>
  username: <%= ENV.fetch('RABBITMQ_USER') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD') %>
